spring.application.name=userService


# Security
spring.security.user.name=user
spring.security.user.password=password

# Server
server.port=8080
server.address=0.0.0.0

spring.profiles.active=${ENV:dev}

