# Database (local Postgres)
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/ecom_website?currentSchema=user_service
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
