spring.application.name=userService

# Database (local Postgres)
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/ecom_website?currentSchema=user_service
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Security
spring.security.user.name=user
spring.security.user.password=password

# Server
server.port=8080
server.address=0.0.0.0
